[package]
name = "voxel-symmetry"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = [
  "pos_y_up", "pos_x_right", "neg_z_forward",
]

# Angles increase in the clockwise order.
clockwise-angles = []

# Exactly one `up` direction feature must be selected
neg_x_up = []
neg_y_up = []
neg_z_up = []
pos_x_up = []
pos_y_up = []
pos_z_up = []

# Exactly one `right` direction feature must be selected.
neg_x_right = []
neg_y_right = []
neg_z_right = []
pos_x_right = []
pos_y_right = []
pos_z_right = []

# Exactly one `forward` direction feature must be selected.
neg_x_forward = []
neg_y_forward = []
neg_z_forward = []
pos_x_forward = []
pos_y_forward = []
pos_z_forward = []

# Pre-configured coordinate systems.
left-hand-y-up = ["pos_y_up", "pos_x_right", "pos_z_forward"]
left-hand-z-up = ["pos_z_up", "pos_x_right", "neg_y_forward"]
right-hand-y-up = ["pos_y_up", "pos_x_right", "neg_z_forward"]
right-hand-z-up = ["pos_z_up", "pos_x_right", "pos_y_forward"]

# https://learnopengl.com/Getting-started/Coordinate-Systems
opengl-coordinate-system = ["right-hand-y-up"]
# https://learn.microsoft.com/en-us/windows/win32/direct3d9/coordinate-systems
directx-coordinate-system = ["left-hand-y-up"]
# https://docs.unity3d.com/6000.3/Documentation/ScriptReference/Vector3.html
unity-coordinate-system = ["left-hand-y-up"]
# https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_3d_scenes/model_export_considerations.html
# https://docs.godotengine.org/en/4.4/classes/class_vector3.html
godot-coordinate-system = ["right-hand-y-up"]
# https://dev.epicgames.com/documentation/unreal-engine/coordinate-system-and-spaces-in-unreal-engine
unreal-coordinate-system = ["pos_z_up", "pos_y_right", "pos_x_forward"]
# https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#coordinate-system-and-units
gltf-coordinate-system = ["pos_y_up", "neg_x_right", "pos_z_forward"]

[dependencies]
isit = { version = "0.1.3", features = ["no-std"] }
paste = "1.0.15"
